"""initial schema

Revision ID: 181a023fc28f
Revises: 
Create Date: 2026-09-16 16:36:25.079637

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '181a023fc28f'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cache_mpes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('uf', sa.String(), nullable=False),
    sa.Column('municipio_ibge', sa.String(), nullable=True),
    sa.Column('cnae_divisao', sa.String(), nullable=False),
    sa.Column('cnae_subclasse', sa.String(), nullable=True),
    sa.Column('qtd_mpes', sa.Integer(), nullable=False),
    sa.Column('periodo_referencia', sa.String(), nullable=True),
    sa.Column('atualizado_em', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('uf', 'municipio_ibge', 'cnae_divisao', 'cnae_subclasse', name='uq_cache_mpe_uf_mun_cnae')
    )
    with op.batch_alter_table('cache_mpes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_cache_mpes_cnae_divisao'), ['cnae_divisao'], unique=False)
        batch_op.create_index(batch_op.f('ix_cache_mpes_municipio_ibge'), ['municipio_ibge'], unique=False)
        batch_op.create_index(batch_op.f('ix_cache_mpes_uf'), ['uf'], unique=False)

    op.create_table('catalogo_materiais',
    sa.Column('codigo', sa.String(), nullable=False),
    sa.Column('descricao', sa.Text(), nullable=True),
    sa.Column('grupo', sa.String(), nullable=True),
    sa.Column('classe', sa.String(), nullable=True),
    sa.Column('cnae_mapeado', sa.String(), nullable=True),
    sa.Column('atualizado_em', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('codigo')
    )
    op.create_table('catalogo_servicos',
    sa.Column('codigo', sa.String(), nullable=False),
    sa.Column('descricao', sa.Text(), nullable=True),
    sa.Column('grupo', sa.String(), nullable=True),
    sa.Column('classe', sa.String(), nullable=True),
    sa.Column('cnae_mapeado', sa.String(), nullable=True),
    sa.Column('atualizado_em', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('codigo')
    )
    op.create_table('contratacoes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('orgao_cnpj', sa.String(), nullable=False),
    sa.Column('orgao_nome', sa.String(), nullable=True),
    sa.Column('ano', sa.Integer(), nullable=False),
    sa.Column('sequencial', sa.Integer(), nullable=False),
    sa.Column('objeto', sa.Text(), nullable=True),
    sa.Column('modalidade', sa.Integer(), nullable=False),
    sa.Column('modalidade_nome', sa.String(), nullable=True),
    sa.Column('valor_estimado', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('esfera', sa.String(), nullable=False),
    sa.Column('uf', sa.String(), nullable=True),
    sa.Column('municipio_ibge', sa.String(), nullable=True),
    sa.Column('exclusiva_mpe', sa.Boolean(), nullable=True),
    sa.Column('data_publicacao', sa.Date(), nullable=False),
    sa.Column('data_abertura_proposta', sa.Date(), nullable=True),
    sa.Column('data_encerramento_proposta', sa.Date(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('raw_json', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('orgao_cnpj', 'ano', 'sequencial', name='uq_contratacao_orgao_ano_seq')
    )
    with op.batch_alter_table('contratacoes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_contratacoes_data_publicacao'), ['data_publicacao'], unique=False)
        batch_op.create_index(batch_op.f('ix_contratacoes_municipio_ibge'), ['municipio_ibge'], unique=False)
        batch_op.create_index(batch_op.f('ix_contratacoes_orgao_cnpj'), ['orgao_cnpj'], unique=False)
        batch_op.create_index(batch_op.f('ix_contratacoes_uf'), ['uf'], unique=False)

    op.create_table('pca_itens',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('orgao_cnpj', sa.String(), nullable=False),
    sa.Column('ano', sa.Integer(), nullable=False),
    sa.Column('catmat_catser', sa.String(), nullable=True),
    sa.Column('descricao', sa.Text(), nullable=True),
    sa.Column('valor_estimado', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('quantidade', sa.Numeric(precision=15, scale=4), nullable=True),
    sa.Column('unidade', sa.String(), nullable=True),
    sa.Column('data_prevista', sa.Date(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('pca_itens', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_pca_itens_orgao_cnpj'), ['orgao_cnpj'], unique=False)

    op.create_table('contratos',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('contratacao_id', sa.Integer(), nullable=True),
    sa.Column('fornecedor_cnpj', sa.String(), nullable=False),
    sa.Column('fornecedor_nome', sa.String(), nullable=True),
    sa.Column('fornecedor_porte', sa.String(), nullable=True),
    sa.Column('valor_contrato', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('data_assinatura', sa.Date(), nullable=True),
    sa.Column('data_vigencia_inicio', sa.Date(), nullable=True),
    sa.Column('data_vigencia_fim', sa.Date(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['contratacao_id'], ['contratacoes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('contratos', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_contratos_contratacao_id'), ['contratacao_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_contratos_fornecedor_cnpj'), ['fornecedor_cnpj'], unique=False)

    op.create_table('cruzamentos',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('contratacao_id', sa.Integer(), nullable=True),
    sa.Column('cnae_divisao', sa.String(), nullable=True),
    sa.Column('cnae_descricao', sa.String(), nullable=True),
    sa.Column('uf', sa.String(), nullable=True),
    sa.Column('municipio_ibge', sa.String(), nullable=True),
    sa.Column('qtd_mpes_regiao', sa.Integer(), nullable=True),
    sa.Column('sinal', sa.String(), nullable=False),
    sa.Column('score', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('detalhes', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['contratacao_id'], ['contratacoes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('cruzamentos', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_cruzamentos_cnae_divisao'), ['cnae_divisao'], unique=False)
        batch_op.create_index(batch_op.f('ix_cruzamentos_contratacao_id'), ['contratacao_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_cruzamentos_uf'), ['uf'], unique=False)

    op.create_table('itens',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('contratacao_id', sa.Integer(), nullable=False),
    sa.Column('numero_item', sa.Integer(), nullable=True),
    sa.Column('catmat_catser', sa.String(), nullable=True),
    sa.Column('descricao', sa.Text(), nullable=True),
    sa.Column('unidade', sa.String(), nullable=True),
    sa.Column('quantidade', sa.Numeric(precision=15, scale=4), nullable=True),
    sa.Column('valor_unitario_estimado', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('valor_total_estimado', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('cnae_mapeado', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['contratacao_id'], ['contratacoes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('itens', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_itens_catmat_catser'), ['catmat_catser'], unique=False)
        batch_op.create_index(batch_op.f('ix_itens_contratacao_id'), ['contratacao_id'], unique=False)

    op.create_table('alertas',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('perfil', sa.String(), nullable=False),
    sa.Column('tipo', sa.String(), nullable=True),
    sa.Column('titulo', sa.String(), nullable=False),
    sa.Column('corpo', sa.Text(), nullable=True),
    sa.Column('uf', sa.String(), nullable=True),
    sa.Column('cnae_divisao', sa.String(), nullable=True),
    sa.Column('contratacao_id', sa.Integer(), nullable=True),
    sa.Column('cruzamento_id', sa.Integer(), nullable=True),
    sa.Column('lido', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['contratacao_id'], ['contratacoes.id'], ),
    sa.ForeignKeyConstraint(['cruzamento_id'], ['cruzamentos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('alertas', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_alertas_uf'), ['uf'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('alertas', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_alertas_uf'))

    op.drop_table('alertas')
    with op.batch_alter_table('itens', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_itens_contratacao_id'))
        batch_op.drop_index(batch_op.f('ix_itens_catmat_catser'))

    op.drop_table('itens')
    with op.batch_alter_table('cruzamentos', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_cruzamentos_uf'))
        batch_op.drop_index(batch_op.f('ix_cruzamentos_contratacao_id'))
        batch_op.drop_index(batch_op.f('ix_cruzamentos_cnae_divisao'))

    op.drop_table('cruzamentos')
    with op.batch_alter_table('contratos', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_contratos_fornecedor_cnpj'))
        batch_op.drop_index(batch_op.f('ix_contratos_contratacao_id'))

    op.drop_table('contratos')
    with op.batch_alter_table('pca_itens', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_pca_itens_orgao_cnpj'))

    op.drop_table('pca_itens')
    with op.batch_alter_table('contratacoes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_contratacoes_uf'))
        batch_op.drop_index(batch_op.f('ix_contratacoes_orgao_cnpj'))
        batch_op.drop_index(batch_op.f('ix_contratacoes_municipio_ibge'))
        batch_op.drop_index(batch_op.f('ix_contratacoes_data_publicacao'))

    op.drop_table('contratacoes')
    op.drop_table('catalogo_servicos')
    op.drop_table('catalogo_materiais')
    with op.batch_alter_table('cache_mpes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_cache_mpes_uf'))
        batch_op.drop_index(batch_op.f('ix_cache_mpes_municipio_ibge'))
        batch_op.drop_index(batch_op.f('ix_cache_mpes_cnae_divisao'))

    op.drop_table('cache_mpes')
    # ### end Alembic commands ###
